### ISSUE TITLE
文档

### ISSUE THREAD

**Issue by cyq7on** [yjc567/HDU_OS_Assignment_2017_SimpleFileSystem#1]
首先，非常感谢lz的分享精神，此次我也希望自己在lz基础上做一些优化。
然后，想问问lz提及的相关文档是否已经完成，能否分享了？

**Comment by yujiachen-y** [comment]
https://blog.csdn.net/dpppBR/article/details/78895262
文档写的不好，这个issue也没能及时回复，有点抱歉哈
